name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'


      - name: Setup Gradle
        uses: gradle/wrapper-action@v2


      - name: Build with Gradle
        run: ./gradlew build --no-daemon


      - name: Run tests
        run: ./gradlew test --no-daemon
