name: CI

on:
  push:
    branches:
      - main  # Izmenit' vetku v zavisimosti ot vashego osnovnogo brancha
  pull_request:
    branches:
      - main  # Izmenit' vetku v zavisimosti ot vashego osnovnogo brancha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Dobavit' shagi dlya sborki proyekta zdes'
      # Primer: Ustanovka zavisimostey, sborka, zapusk testov, itd.

      # Primer shaga dlya sborki s pomoshch'yu Node.js
      - name: Install dependencies
        run: npm install

      # Primer shaga dlya zapuska testov
      - name: Run tests
        run: npm test

      # Primer shaga dlya vozmozhnosti vypolneniya skriptov komandnoy stroke
      - name: Execute custom script
        run: |
          echo "Custom script executed"